[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "HOST=0.0.0.0 PORT=$PORT node ./dist/server/entry.mjs"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
 healthCheckPath = "/"
 healthCheckTimeout = 100
