[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node ./dist/server/entry.mjs"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.healthcheck]
path = "/api/health"
timeout = 100
interval = 30
